POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Giordano Bruno",
  "number": "45-78-97654"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Al",
  "number": "55-44-98765"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Giordano Bruno",
  "number": "123"
}