POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "Atualização 2.0 do S6 robusto"
}

###

POST http://localhost:3001/api/notes
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJwb3J0byIsImlkIjoiNWVhYTFhNWI3MzZkY2EzODFjNTJhMmVlIiwiaWF0IjoxNTg4MjA5MjEwfQ.JKm5K66dP8b3H1me99iuYFh0qg3xGcxeh8PT-_G5U1U

{
    "content": "Single Page Apps use token authentication",
    "important": true
}

###

POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "rporto",
    "name": "Renato Porto",
    "password": "1q2w3e$"
}

###

POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "rporto",
    "password": "1q2w3e$"
}